config/routes.rb
Rails.application.routes.draw do
  get '/', to: 'site#home'
  get '/contact', to: 'site#contact'
  get '/calculator', to: 'site#calculator'
  post '/calculate', to: 'site#calculate'
  resources :projects, only: [:index, :show, :new, :create] do 
    resources :time_entries
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/project.rb
class Project < ApplicationRecord
	has_many :time_entries
	
	def self.clean_old(date = 1.week.ago)
		Project.where('created_at < ?', date).destroy_all
	end
end

app/models/time_entry.rb
class TimeEntry < ApplicationRecord
	belongs_to :project
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
	def index
		@projects = Project.order(created_at: :desc)
	end

	def show
		@project = Project.find_by(id: params[:id])
		unless @project
			render "project_not_found"
		end
	end

	def new
		@project = Project.new
	end

    def create
    	@project = Project.new(name: params[:project][:name], description: params[:project][:description])
    	@project.save

    	redirect_to "/projects/#{@project.id}"
    end
end

app/controllers/site_controller.rb
class SiteController < ApplicationController
	def home
	end

	def contact	
	end

	def calculator
	end

	def calculate
		@num1 = params[:first_num].to_i
		@num2 = params[:second_num].to_i
		@result = @num1 + @num2
		render 'calculate'
	end
end

app/controllers/time_entries_controller.rb
class TimeEntriesController < ApplicationController
	def index
		@project = Project.find(params[:project_id])
		@entries = @project.time_entries.where('created_at > ?', 1.month.ago.end_of_month)
	end

	def new
		@project = Project.find(params[:project_id])
		@entry = @project.time_entries.new
	end

	def create
		@project = Project.find(params[:project_id])
		
		@entry = @project.time_entries.new(
			hours: params[:time_entry][:hours], 
			minutes: params[:time_entry][:minutes], 
			date: params[:time_entry][:date])
		if @entry.save
			redirect_to "/projects/#{@project.id}/time_entries"
		else
			render "new"
		end
	end

	def edit
		@project = Project.find params[:project_id]
		@entry = @project.time_entries.find params[:id]
	end

	def update
		@project = Project.find(params[:project_id])
		@entry = @project.time_entries.find params[:id]
		if @entry.update(entry_params)
			redirect_to "/projects/#{@project.id}/time_entries"
		else
			render "edit"
		end
	end

	def destroy
		@project = Project.find(params[:project_id])
		@entry = @project.time_entries.find params[:id]
		if @entry.destroy
			redirect_to "/projects/#{@project.id}/time_entries"
		else
			render "index"
		end

	end


	private

	def entry_params
		params.require(:time_entry).permit(:hours, :minutes, :date)
	end



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/helpers/time_entries_helper.rb
module TimeEntriesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Timertracking</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/projects/index.html.erb
<h2>Projects</h2>
<ul>
	<% @projects.each do |project| %>
		<% if project.description != "" %>
			<li>Your wonderful project: <strong><%=project.name%></strong> has this shitty description: <strong><%=project.description%></strong></li>
		<% end %>
	<% end %>
</ul>

<div><%= link_to "Create new project", "/projects/new" %></div>
<%= link_to "Home", "/" %>

app/views/projects/new.html.erb
<h1>Add a project:</h1>

<%= form_for @project do |f| %>
	<%= f.label :name %>
	<%= f.text_field :name %>

	<%= f.label :description %>
	<%= f.text_area :description %>

	<%= f.button %>
<% end %>
<br>
<%= link_to "Home", "/" %>

app/views/projects/project_not_found.html.erb
<h3>Sorry, your project was not found</h3>

app/views/projects/show.html.erb
<h2>Project <%= @project.name %></h2>

<% if @project.description.present? %>
	<p><%= @project.description %></p>
<% end -%>

<%= link_to "Home", "/" %>

app/views/site/calculate.html.erb
<p>The result of <%= @num1 %> + <%= @num2 %> is <%= @result %></p>

<%= link_to "Home", "/" %>

app/views/site/calculator.html.erb
<form action="/calculate" method="POST">
	<input type="text" name="first_num" placeholder="First number">
	<input type="text" name="second_num" placeholder="Second Number">
	<input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
	<button type="submit">Add</button>
</form>

<%= link_to "Home", "/" %>

app/views/site/contact.html.erb
<h1>Contact Us!</h1>
<p>Want to talk to us? hello@timetracker.com</p>

<%= link_to "Home", "/" %>

app/views/site/home.html.erb
<h1>Welcome to the Time Tracking tool! oh, and a calculator</h1>

<p>@AJoeRed Powered</p>

<div><%= link_to "Contact Us", "/contact" %></div>
<div><%= link_to "Calculator", "/calculator" %></div>
<div><%= link_to "Projects", "/projects" %></div>


<%= image_tag "Dramatic-Glasses.gif", alt: "Dramatic Glasses", class: "image" %>
<%= image_tag "Dramatic-Glasses.gif", alt: "Dramatic Glasses", class: "image" %>
<%= image_tag "Dramatic-Glasses.gif", alt: "Dramatic Glasses", class: "image" %>
<%= image_tag "Dramatic-Glasses.gif", alt: "Dramatic Glasses", class: "image" %>

app/views/time_entries/_form.html.erb
<%= form_for [@project, @entry] do |f| %>
	<%= f.label :hours %>
	<%= f.text_field :hours %>
	<br>
	<%= f.label :minutes %>
	<%= f.text_field :minutes %>
	<br>
	<%= f.label :date %>
	<%= f.date_field :date %>
	<br>
	<%= f.button %>
<% end %>

<br>
<%= link_to "Home", "/" %>

app/views/time_entries/edit.html.erb
<h4>Edit Time Entry <%=@entry.id %> for <%= @project.name %></h4>
<%= render "form" %>

app/views/time_entries/index.html.erb
<h2>Project <%= @project.name %></h2>

<ul>
	<% @entries.each do |entry| %>
		<li> 
		<%=entry.hours%> h, 
		<%=entry.minutes%> m - 
		<%=entry.date%> 
		<%= link_to "Edit", "/projects/#{@project.id}/time_entries/#{entry.id}/edit"%>
		<%= link_to("Delete", project_time_entry_path(@project, entry), method: :delete, data: { confirm: 'Are you sure?'})%> 
		</li>
	<% end %>
</ul>


<br>
<%= link_to "Home", "/" %>
<%= link_to "Projects", "/projects" %>

app/views/time_entries/new.html.erb
Create Time Entry for <%= @project.name %>
<%= render "form" %>